### ISSUE TITLE
Can't make references work in lsp! HELP!

### ISSUE THREAD

**Issue by gbmarc1** [weibolu-rm/nvimdots#1]
I am in a python file and `gr` does not work
I am having `[telescope.builtin.lsp_*]: server does not support referencesProvider
`pyright` supports references right?

**Comment by weibolu-rm** [comment]
@gbmarc1 what does `:LspInfo` show?

Did you install the LSPs using `:LspInstallInfo`?

**Comment by gbmarc1** [comment]
Loll no idea that we needed to do this! It worked by doing `:LspInstall pyright`
thanks!

**Comment by weibolu-rm** [comment]
true I forgot to include it in the readme. Added, thanks!
